import './browser-environment.mjs';
import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const artifacts = new URL('../docs/verification/', import.meta.url);
await fs.mkdir(artifacts, { recursive: true });
try {
  await page.goto('http://127.0.0.1:8011/dashboard/');
  await page.getByRole('heading', {name:'What would you like to do?',exact:true}).waitFor();
  await page.getByRole('navigation').getByRole('button',{name:'Camera registry',exact:true}).click();
  await page.getByRole('heading', { name: 'Camera registry & GIS', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Add camera', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Camera onboarding' });
  await dialog.getByLabel('Camera ID', {exact:true}).fill('BROWSER-TEST');
  await dialog.getByLabel('Camera name', {exact:true}).fill('Browser test camera');
  await dialog.getByLabel('Location', {exact:true}).fill('Synthetic browser fixture');
  await dialog.getByLabel('Latitude', {exact:true}).fill('22.4');
  await dialog.getByLabel('Longitude', {exact:true}).fill('73.2');
  await dialog.getByLabel('Coordinate provenance').selectOption('REPRESENTATIVE');
  await dialog.getByRole('button', {name:'Save camera'}).click();
  await dialog.waitFor({state:'hidden'});
  await page.getByText('Camera saved to the registry.', {exact:true}).waitFor();
  await page.screenshot({path:fileURLToPath(new URL('registry.png',artifacts)),fullPage:true});
  // Synthetic survey geometry is confined to the isolated fixture database.
  const polygon = (id,kind,right) => ({type:'Feature',properties:{id,name:`Synthetic ${id}`,kind,provenance:'VERIFIED',camera_id:kind==='CAMERA'?'TEST-A':null},geometry:{type:'Polygon',coordinates:[[[73,22],[right,22],[right,22.1],[73,22.1],[73,22]]]}});
  const survey = {type:'FeatureCollection',features:[polygon('browser-area','AREA',73.2),polygon('browser-footprint','CAMERA',73.1)]};
  await page.getByRole('button',{name:'Coverage',exact:true}).click();
  await page.getByLabel('Import survey GeoJSON').setInputFiles({name:'synthetic-survey.geojson',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(survey))});
  await page.getByText('Synthetic browser-area: 50% covered',{exact:true}).waitFor();
  await page.screenshot({path:fileURLToPath(new URL('coverage-synthetic.png',artifacts)),fullPage:true});
  const coverageDownload = page.waitForEvent('download');
  await page.getByRole('button',{name:'Download coverage report',exact:true}).click();
  const report = await coverageDownload;
  assert.equal(report.suggestedFilename(),'geographic-coverage.json');
  await page.getByRole('button',{name:'Watchlist',exact:true}).click();
  await page.getByRole('button',{name:'Add vehicle',exact:true}).click();
  const watch = page.getByRole('dialog',{name:'Watchlist entry'});
  await watch.getByLabel('Registration',{exact:true}).fill('TEST99');
  await watch.getByLabel('Description',{exact:true}).fill('Synthetic browser test; not an official record');
  await watch.getByRole('button',{name:'Save entry'}).click();
  await watch.waitFor({state:'hidden'});
  await page.getByText('TEST99',{exact:true}).waitFor();
  await page.getByRole('navigation').getByRole('button',{name:'Find vehicle',exact:true}).click();
  await page.getByLabel('Vehicle registration').fill('TEST123');
  await page.locator('main').getByRole('button',{name:'Find vehicle',exact:true}).click();
  await page.getByRole('heading',{name:'TEST123',exact:true}).waitFor();
  await page.getByText(/2 observations .* 2 cameras .* timestamps shown in IST/).waitFor();
  assert.equal(await page.locator('.police-table-wrap tbody tr').count(),2);
  const downloaded = page.waitForEvent('download');
  await page.getByRole('button',{name:'Export history',exact:true}).click();
  assert.equal((await downloaded).suggestedFilename(),'vehicle-history.csv');
  await page.screenshot({path:fileURLToPath(new URL('vehicle-trace.png',artifacts)),fullPage:true});
  await page.getByRole('button',{name:'Alerts',exact:true}).click();
  await page.getByRole('heading',{name:'Latest matches',exact:true}).waitFor();
  await page.getByRole('button',{name:'Acknowledge',exact:true}).first().click();
  await page.getByText('Alert acknowledged.',{exact:true}).waitFor();
  await page.screenshot({path:fileURLToPath(new URL('alerts.png',artifacts)),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Open navigation',exact:true}).click();
  await page.getByRole('navigation').getByRole('button',{name:'Camera registry',exact:true}).click();
  await page.getByRole('heading',{name:'Camera registry & GIS',exact:true}).waitFor();
  await page.screenshot({path:fileURLToPath(new URL('mobile.png',artifacts)),fullPage:true});
  assert.equal(errors.length,0,errors.join('\n'));
  console.log('PASS: browser onboarding, watchlist entry, two-camera trace, CSV download, alert acknowledgement, mobile rendering; no JS exceptions. Synthetic fixtures only.');
} finally { await browser.close(); }
