services:
  app:
    build:
      args:
        TORCH_INDEX_URL: https://download.pytorch.org/whl/cu124
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
